### ISSUE TITLE
Documentation for build doesn't complete successfully

### ISSUE THREAD

**Issue by ivandov** [InCuca/vue-loopback#9]
Hi, Thank you for your contribution. I think it's a great starting point for using Loopback with Vue. 

I cloned the repo and followed the local setup instructions as written. `npm run dev` works as expected. 

When I do the following, I get an error.
1. `npm run build`
1. `cd build`
1. `npm run start`

```
Ivans-MacBook-Pro:build ivandov$ npm run start

> test@1.0.0 start /Users/ivandov/git/mfaas/test/build
> (type ./build/index.js && node ./build/index.js) || node ./index.js

sh: line 0: type: ./build/index.js: not found
/Users/ivandov/git/mfaas/test/node_modules/loopback-datasource-juggler/lib/mixins.js:50
      throw new Error(errMsg);
      ^

Error: Model "Account" uses unknown mixin: TimeStamp
    at MixinProvider.applyMixin (/Users/ivandov/git/mfaas/test/node_modules/loopback-datasource-juggler/lib/mixins.js:50:13)
    at ModelBuilder.defineClass [as define] (/Users/ivandov/git/mfaas/test/node_modules/loopback-datasource-juggler/lib/model-builder.js:649:27)
    at Function.ModelClass.extend (/Users/ivandov/git/mfaas/test/node_modules/loopback-datasource-juggler/lib/model-builder.js:447:33)
    at Registry.createModel (/Users/ivandov/git/mfaas/test/node_modules/loopback/lib/registry.js:122:25)
    at /Users/ivandov/git/mfaas/test/node_modules/loopback-boot/lib/executor.js:245:24
    at Array.forEach (<anonymous>)
    at defineModels (/Users/ivandov/git/mfaas/test/node_modules/loopback-boot/lib/executor.js:229:23)
    at setupModels (/Users/ivandov/git/mfaas/test/node_modules/loopback-boot/lib/executor.js:197:3)
    at execute (/Users/ivandov/git/mfaas/test/node_modules/loopback-boot/lib/executor.js:40:3)
    at bootLoopBackApp (/Users/ivandov/git/mfaas/test/node_modules/loopback-boot/index.js:154:3)
    at Object.<anonymous> (/Users/ivandov/git/mfaas/test/build/server/server.js:41:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 start: `(type ./build/index.js && node ./build/index.js) || node ./index.js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ivandov/.npm/_logs/2018-06-13T17_05_54_865Z-debug.log
```

**Comment by klarkc** [comment]
Hey thanks for the report!

I believe it's fixed now, please let me know if you have any other issues.
